/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IntefaceGrafica;

/**
 *
 * @author ThainaRibeiro
 */
public class GUI_Caulculadora extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Aula2
     */
    public GUI_Caulculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_campo1 = new javax.swing.JTextField();
        txt_campo2 = new javax.swing.JTextField();
        bt_soma = new javax.swing.JButton();
        bt_subtracao = new javax.swing.JButton();
        bt_divisao = new javax.swing.JButton();
        bt_multiplicacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_campo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_campo1ActionPerformed(evt);
            }
        });

        bt_soma.setText("+");
        bt_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_somaActionPerformed(evt);
            }
        });

        bt_subtracao.setText("-");
        bt_subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_subtracaoActionPerformed(evt);
            }
        });

        bt_divisao.setText("/");
        bt_divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_divisaoActionPerformed(evt);
            }
        });

        bt_multiplicacao.setText("*");
        bt_multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_multiplicacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_divisao)
                    .addComponent(bt_subtracao)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_soma))
                    .addComponent(bt_multiplicacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_campo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_soma))
                .addGap(18, 18, 18)
                .addComponent(bt_subtracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_multiplicacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_divisao)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_somaActionPerformed
        // TODO add your handling code here:
        Calculadora calculadora= new Calculadora();
        float campo1 = Integer.parseInt(txt_campo1.getText());
        float campo2 = Integer.parseInt(txt_campo2.getText());
        calculadora.setCampo1(campo1);
        calculadora.setCampo2(campo2);
        int soma = calculadora.getSoma();
        //int soma = campo1+campo2;
         System.out.println("Soma eh:"+soma);
        
    }//GEN-LAST:event_bt_somaActionPerformed

    private void txt_campo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_campo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_campo1ActionPerformed

    private void bt_subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_subtracaoActionPerformed
        // TODO add your handling code here:
         Calculadora calculadora= new Calculadora();
        float campo1 = Float.parseFloat(txt_campo1.getText());
         float campo2 = Float.parseFloat(txt_campo2.getText());
       calculadora.setCampo1(campo1);
       calculadora.setCampo2(campo2);
        float subtracao = calculadora.getSubtracao();
        //int subtracao = campo1-campo2;
        //calculadora.subtrair(campo1, campo2);
        
       
               
         System.out.println("Subtracao eh:"+subtracao);
        
    }//GEN-LAST:event_bt_subtracaoActionPerformed

    private void bt_multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_multiplicacaoActionPerformed
        // TODO add your handling code here:
         Calculadora calculadora= new Calculadora();
         float campo1 = Float.parseFloat(txt_campo1.getText());
         float campo2 = Float.parseFloat(txt_campo2.getText());
         //float multiplicacao = campo1*campo2;
         calculadora.setCampo1(campo1);
         calculadora.setCampo2(campo2);
         float multiplicacao = calculadora.getMultiplicacao();
         System.out.println("Multiplicação eh:"+multiplicacao);
    }//GEN-LAST:event_bt_multiplicacaoActionPerformed

    private void bt_divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_divisaoActionPerformed
        // TODO add your handling code here:
         Calculadora calculadora= new Calculadora();
         float campo1 = Float.parseFloat(txt_campo1.getText());
         float campo2 = Float.parseFloat(txt_campo2.getText());
         calculadora.setCampo1(campo1);
         calculadora.setCampo2(campo2);
         float divisao = calculadora.getDivisao();
         //float divisao = campo1/campo2;
         System.out.println("Divisão eh:"+divisao);
                                                
    }//GEN-LAST:event_bt_divisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Caulculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Caulculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Caulculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Caulculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Caulculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_divisao;
    private javax.swing.JButton bt_multiplicacao;
    private javax.swing.JButton bt_soma;
    private javax.swing.JButton bt_subtracao;
    private javax.swing.JTextField txt_campo1;
    private javax.swing.JTextField txt_campo2;
    // End of variables declaration//GEN-END:variables
}
